name: cos
description: Control Ã“rdenes de Servicio
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  # bloc: ^8.1.4
  csv: ^6.0.0
  flutter_dotenv: ^5.2.1
  device_info: ^2.0.3
  file_picker: ^10.1.2
  file_saver: ^0.2.14
  firebase_analytics: ^11.4.5
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_material_color_picker: ^1.2.0
  flutter_native_splash: ^2.2.9
  gap: ^3.0.1
  get: ^4.6.6
  http: ^1.1.0
  image_gallery_saver: ^2.0.3
  intl: ^0.20.2
  localstorage: ^6.0.0
  mime: ^2.0.0
  path_provider: ^2.1.3
  permission_handler: ^12.0.0+1
  postgres: ^2.5.4
  statistics: ^1.2.0
  supabase_flutter: ^2.8.4
  translator: ^1.0.3+1
  # universal_html: ^2.2.4
  url_launcher: ^6.2.4
  # flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - .env

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "images/customer.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   web:
#     generate: true
#     image_path: "images/customer.png"
#     background_color: "#dce4e8"
#     theme_color: "#dce4e8"
#   #to run flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  color: "#F1F1F1"
  image: images/customer.png
  #to run flutter pub run flutter_native_splash:create